var arrLang = {
    'en': {
      'HOME': 'HOME',
      'SHOP': 'SHOP',
      'ABOUT': 'ABOUT',
      'JOURNAL': 'JOURNAL',
      'CONTACT': 'CONTACT',
      'organic': 'Organic cotton, free from harmful substances.',
      'eco': 'ECO-RELAX. MADE WITH 100% GOTS',
      'button1': 'SHOP THE COLLECTION',
      'new': 'Shop New in',
      'now': 'SHOP NOW',
      'bestsellers': 'Shop Bestsellers',
      'textshop': 'Shop hundreds of enamel pins from artists.'
      +'The best cool pin badges to decorate your backpack,'
       +'denim jean jacket, lapel,'
     + 'and festival hat for sale in our online store.',
      'FREE': 'CRUELTY FREE',
      'digital': 'Free digital proofs and best design advice',
      'vegan': '100% VEGAN',
      'always': 'You can always start with 50 pcs here',
      'NATURAL': 'NATURAL INGREDIENTS',
      'Get': 'Get excellent pins or have your money back',
      'HOME': 'HOME',
      'SHOP': 'SHOP',
      'ABOUT': 'ABOUT',
      'JOURNAL': 'JOURNAL',
      'Hard': 'Hard BOILED Egg and Avocado',
      'BOMB': 'BOMB! Enamel Pin',
      'Pineapple': 'Pineapple Charm Pendant',
      'powerhouse': 'From our powerhouse to your house.',
      'Lorem': 'Lorem ipsum dolor sit amet,'
      +'consectetur adipiscing elit.'
      +'Suspendisse varius enim in eros elementum tristique.',
      'Use': 'Use this text to describe the first step...',
      'second': '...the second step is following here...',
      'aaand': '...aaand the third one...',
      'last': '...This is the last fourth step of how it works.',
      'rest': 'Get the rest of the story',
      'Best': '“Best templates and support out there!'
      +'They are always happy to help with any issues you may be having '
     +'or even just showing how to edit things.”',
      'Sam': 'Sam (Trustpilot)',
      'personal': 'A personal commerce expert at your fingertips',
      'Lorem1': 'Lorem ipsum dolor sit amet,'
      +'consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.'
      +'Duis cursus, mi quis viverra ornare, eros dolor interdum nulla,'
      +'ut commodo diam libero vitae erat.',
      'started': 'Get started',
      'QUESTIONS': 'YOU HAVE QUESTIONS',
      'We’ve': 'We’ve got answers.',
      'offer': 'Do you offer educational discounts?',
      'add': 'add',
      'Which': 'Which payment methods do you accept?',
      'license': 'I have a license. Can I switch to a subscription?',
      'trial': 'Start free trial',
      'lorem': '30 day trial lorem ipsum dolor.',
      'Follow': 'Follow',
      'JOURNAL': 'JOURNAL',
      'Instagram': 'on Instagram',
      'buttonFollow': 'Follow @salma',
      'This': 'This is some text from your @instagram feed.',
      'Sign': 'Sign up for email newsletters from SALMA!',
      'learn': 'To learn how we process your data, visit our',
      'Privacy': 'Privacy Notice',
      'can': '. You can',
      'unsubscribe': 'unsubscribe',
      'any': 'at any time without costs.',
      'Social': 'Social Links',
      'products': 'All products',
      'Fruit': 'Fruit',
      'Custom': 'Custom',
      'Cute': 'Cute',
      'LEARN': 'LEARN',
      'FAQ': 'FAQ',
      'Template': 'TEMPLATE',
      'Style': 'Style',
      'Instructions': 'Instructions',
      'Licensing': 'Licensing',
      'Changelog': 'Changelog',
      'Templates': 'More Templates',
    },
    'ru': {
      'HOME': 'Дом',
      'SHOP': 'Магазин',
      'ABOUT': 'О нас',
      'JOURNAL': 'Журнал',
      'CONTACT': 'Контакты',
      'organic': 'Органический хлопок, безвредный.',
      'eco': 'ЭКО-РЕЛАКС. ИЗГОТОВЛЕНО ИЗ 100% ГОТСА',
      'button1': 'ПОКУПАЙТЕ КОЛЛЕКЦИЮ В МАГАЗИНЕ',
      'new': 'Новый магазин в',
      'now': 'ДЕЛАЙТЕ ПОКУПКИ ПРЯМО СЕЙЧАС',
      'bestsellers': 'Магазин бестселлеров',
      'textshop': 'Приобретите эмалевые булавки от художников.'
      +'Лучшие значки-булавки для украшения вашего рюкзака,'
       +'джинсовая куртка из денима с отворотом,'
     + 'и праздничная шляпа для продажи в нашем интернет-магазине.',
      'FREE': 'без жестокости',
      'digital': 'Бесплатные цифровые доказательства и рекомендации по дизайну',
      'vegan': '100% веган',
      'always': 'Вы всегда можете начать с 50 штук здесь',
      'NATURAL': 'НАТУРАЛЬНЫЕ ИНГРЕДИЕНТЫ',
      'Get': 'отличные булавки или получите свои деньги обратно',
      'Hard': 'Сваренное вкрутую яйцо и авокадо',
      'BOMB': 'БОМБА! Эмалевый штифт',
      'Pineapple': 'Подвеска с ананасовым шармом',
      'powerhouse': 'От нашей электростанции до дома.',
      'Lorem': 'Морковь Lorem ipsum,'
      +'элитный орел.'
      +'Это самый потрясающий элемент в мире.',
      'Use': 'Используйте этот текст для описания первого шага...',
      'second': '...здесь следует второй шаг...',
      'aaand': '...аа и третий...',
      'last': '..Это последний четвертый шаг того, как это работает.',
      'rest': 'Узнайте остальную часть истории',
      'Best': '“Лучшие шаблоны и поддержка в мире!'
      +'Они всегда рады помочь с  проблемами, которые могут возникнуть '
     +'или даже просто показываю, как что-то редактировать.”',
      'Sam': 'Сэм (доверенный пилот)',
      'personal': 'Личный эксперт по коммерции у вас под рукой',
      'Lorem1': 'Морковь Lorem ipsum,'
      +'элитный орел. Это самый потрясающий элемент в мире.'
      +'Я хочу жить, я хочу жить, у меня нет боли.,'
      +'тихая тишина была свободна.',
      'started': 'Начать',
      'QUESTIONS': 'У ВАС ЕСТЬ ВОПРОСЫ',
      'We’ve': 'У нас есть ответы.',
      'offer': 'Предлагаете ли вы скидки на обучение?',
      'add': 'добавлять',
      'Which': 'Какие способы оплаты вы принимаете?',
      'license': 'У меня есть лицензия. Могу ли я перейти на подписку?',
      'trial': 'Запустите бесплатную пробную версию',
      'lorem': '30-дневная пробная версия lorem ipsum dolor.',
      'Follow': 'Следовать',
      'Instagram': 'в Instagram',
      'buttonFollow': 'Следовать @salma',
      'This': 'Это фрагмент текста из вашей ленты @instagram.',
      'Sign': 'Подпишитесь на рассылку новостей по электронной почте от SALMA!',
      'learn': 'Чтобы узнать, как мы обрабатываем ваши данные, посетите наш сайт',
      'Privacy': 'конфиденциальность',
      'can': '. Ты можешь',
      'unsubscribe': 'отписаться',
      'any': 'в любое время без каких-либо затрат.',
      'Social': 'Социальные связи',
      'products': 'Все продукты',
      'Fruit': 'Фрукты',
      'Custom': 'Обычай',
      'Cute': 'Милый',
      'LEARN': 'учить',
      'FAQ': 'FAQ',
      'Template': 'шаблон',
      'Style': 'Стиль',
      'Instructions': 'Инструкции',
      'Licensing': 'Лицензирование',
      'Changelog': 'Журнал изменений',
      'Templates': 'Дополнительные шаблоны',
      'This': 'Это фрагмент текста из вашей ленты @instagram.',
    }
  }